
name: Demo

on:
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: ""
        type: boolean
        default: false

jobs:
  Greeting:
   

  Job1:
    runs-on: ubuntu-latest
    needs: [Greeting]

