name: Demo trigger events
on:
  # Webhook events
  push:
    branches:
      - main
      - feat/*
  pull_request: 
    branches:
      - main
  issues:
    types:
      - opened
      - closed
  # Scheduled events
  schedule:
    - cron: 0 0 * * *
    - cron: 0 9 * * 0
  # Manual events
  workflow_dispatch: 
    inputs:
      yourName:
        required: true
        default: My friend
      areYouFeelingGood:
        required: true
        type: boolean
      howDoYouFindGithubActions:
        required: false
        type: choice
        options:
          - Awesome
          - Okay
          - Na
jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting step
        run: echo Hello world!
  job2:
    runs-on: utuntu-latest
    needs:
    - Greeting
    steps:
      - name: Step2
        run: echo "${{github.actor}} is learning GitHub Actions"
      - name: Step3
        run: echo "Great"
        if: ${{inputs.areYouFeelingGood}}
      - name: Step4
        run: echo "NO worries. I am here with you"
        if:  ${{inputs.howDoYouFindGithubActions}}
      
      
  
