
name: Demo

on:
  # webhook event#
  push:
    branches: 
      - main
      - Task/*
      - feat/*
  pull_request:
    branches:
      - main
  issues:
    types:
      - closed
      - opened

  # schedule event
  schedule:
    - cron: 0 12 * * *
    - cron: 0 9 * * 0  
  # manual event
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good?"
        type: boolean
        default: false
env:
  MY_VAR: Nilesh
  MY_GREETINGS: Hallo

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from Greeting!"
        if: ${{env.MY_VAR == 'Nilesh'}}

  Job2:
    runs-on: ubuntu-latest
    env:
      MY_GREETINGS: Good morning
    needs: [Job1]
    steps:
      - name: Step2
        run: echo "${{ github.actor }} is learning GitHub Actions."

      - name: Step3
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "Great!"

      - name: Step4
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "I am not well!"
      - name: step5
        run: echo ${{env.MY_GREETINGS}} ${{env.MY_VAR}}
