name: Demo trigger events

on:
  # we have webhook events
  push: 
    branches: 
      - main
      - feat/*
  # scheduled events
  # manual events 

jobs:
  Greeting: 
      run-on: defaults:
        steps: 
          - name: Greeting step
            run: echo "Hello World"
